name: Generate PDF Documentation
on:
  push:
    paths:
      - 'README.md'
    branches:
      - main

jobs:
  convert_to_pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended texlive-extra-utils texlive-latex-extra

      - name: Create PDF style template
        run: |
          cat > template.tex << 'EOL'
          \documentclass[11pt]{article}
          \usepackage[utf8]{inputenc}
          \usepackage{geometry}
          \usepackage{hyperref}
          \usepackage{listings}
          \usepackage{xcolor}
          \usepackage{fancyhdr}
          
          \geometry{a4paper, margin=1in}
          
          \definecolor{codegray}{rgb}{0.95,0.95,0.95}
          \definecolor{codegreen}{rgb}{0,0.6,0}
          \definecolor{backcolour}{rgb}{0.95,0.95,0.95}
          
          \lstdefinestyle{mystyle}{
              backgroundcolor=\color{backcolour},   
              basicstyle=\ttfamily\small,
              breakatwhitespace=false,         
              breaklines=true,                 
              captionpos=b,                    
              keepspaces=true,                 
              numbers=left,                    
              numbersep=5pt,                  
              showspaces=false,                
              showstringspaces=false,
              showtabs=false,                  
              tabsize=2
          }
          
          \lstset{style=mystyle}
          
          \pagestyle{fancy}
          \fancyhf{}
          \rhead{Go2 WiFi Setup}
          \lhead{\today}
          \cfoot{\thepage}
          
          \begin{document}
          $body$
          \end{document}
          EOL

      - name: Convert README to PDF
        run: |
          pandoc README.md \
            --from markdown \
            --template template.tex \
            --pdf-engine=xelatex \
            --highlight-style=tango \
            --toc \
            -o README.pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: README.pdf

      - name: Update Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Delete previous release if it exists
          gh release delete latest --cleanup-tag || true
          
          # Create new release
          gh release create latest README.pdf \
            --title "Latest Documentation" \
            --notes "Automatically generated documentation from README.md" \
            --prerelease